---
abstract: lib/Statistics/Sequences/Joins.pm
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Sequences-Joins
provides:
  Statistics::Sequences::Joins:
    file: lib/Statistics/Sequences/Joins.pm
    version: 0.06
requires:
  List::AllUtils: 0.03
  Statistics::Sequences: 0.051
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
